#!/bin/bash
COMMAND=`basename $0`

usage_exit() {
  echo "USAGE: $COMMAND [-s separator] [startDate [increment]] endDate" 1>&2
  exit 1
}

SEPARATOR=""

while getopts s: OPTION; do
  case $OPTION in
    s ) SEPARATOR="$OPTARG" ;;
    * ) usage_exit ;;
  esac
done
shift $(($OPTIND - 1))

FORMAT="%Y$SEPARATOR%m$SEPARATOR%d"

if [ $# -eq 1 ]; then
  startDate=`date +%Y%m%d`
  increment=1
  endDate=`date +%Y%m%d -d $1` || echo "error: invalid endDate"
elif [ $# -eq 2 ]; then
  startDate=`date +%Y%m%d -d $1` || echo "error: invalid startDate"
  increment=1
  endDate=`date +%Y%m%d -d $2` || echo "error: invalid endDate"
elif [ $# -eq 3 ]; then
  startDate=`date +%Y%m%d -d $1` || echo "error: invalid startDate"
  increment=`expr 0 + "$2"`
  if [ $? -ge 2 ]; then
    echo "error: invalid increment"
  fi
  endDate=`date +%Y%m%d -d $3` || echo "error: invalid endDate"
else
  usage_exit
fi

if [ -z "$startDate" ] || [ -z "$increment" ] || [ -z "$endDate" ]; then
  exit 1
fi

if [ $increment -ge 0 ]; then
  while [ $startDate -le $endDate ]; do
    echo `date +"$FORMAT" -d $startDate`
    startDate=`date +%Y%m%d -d "$startDate + $increment day"`
  done
else
  while [ $startDate -ge $endDate ]; do
    echo `date +"$FORMAT" -d $startDate`
    startDate=`date +%Y%m%d -d "$startDate + $increment day"`
  done
fi

exit
